# Doc: http://docs.travis-ci.com/user/build-configuration/

language: ruby

rvm:
  - "1.9"
  - "2.0"
  - "2.1"

sudo: false

before_install:
  # libruby.so
  - export LD_LIBRARY_PATH=$HOME/.rvm/rubies/`rvm-prompt i v p`/lib:$LD_LIBRARY_PATH

  # get vim source
  - mkdir -p $HOME/local/src
  - pushd $HOME/local/src
  - apt-get source vim
  - cd vim-*

  # build vim
  # TODO: --enable-luainterp
  - ./configure
    --with-features=huge
    --enable-rubyinterp
    --enable-gui=gtk2
    --prefix=$HOME/local
  - make -j4 && make install
  - hash -r
  - popd

  # --enable-gui is required to enable client/server feature
  - which vim
  - vim --version
  - which gvim
  - gvim --version

install:
  - travis_retry bundle install --jobs 4 --path vendor/bundle

before_script:
  - sh -e /etc/init.d/xvfb start
  - bundle exec sspm install example-repo

script:
  - bundle exec rake spec

env:
  global:
    - DISPLAY=:99.0
    - SOCIAL_SNIPPET_SSPM_HOST=sspm-test.herokuapp.com
    - PATH=$HOME/local/bin:$PATH

cache:
  directories:
    - vendor/bundle
    - $HOME/local/src
